name: initialize

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository != 'parro-it/gomod'
    steps:
      - name: Setup tools
        run: |
          echo $PWD
          curl -o addrepo https://github.com/parrogo/ccaddrepo/releases/download/v1.1.1/addrepo
          curl -o setsecret https://github.com/parrogo/ccaddrepo/releases/download/v1.1.1/setsecret
          chmod +x addrepo setsecret
          echo addrepo `./addrepo -v`
          echo setsecret `./setsecret -v`
            
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Enable repo on codeclimate  
        env:
          CC_TOKEN: ${{ secrets.CC_TOKEN }}
          GH_WORKFLOW: ${{ secrets.GH_WORKFLOW }}
        run: ./addrepo | ./setsecret

      - name: Run repo initialization
        env:
          GITHUB_TOKEN: ${{ secrets.GH_WORKFLOW }}
        run: |
          rm .github/workflows/initialize.yml
          echo Initialize workflow removed

          go get github.com/parro-it/templatedir/cli/tmpldir@v0.0.5
          echo parro-it/templatedir installed

          tmpldir
      
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Initialization
